"""Shared data models for the build loop.

Every agent reads and writes these structures. This is the contract layer —
if you change a schema, every agent that touches it must be updated.

All persisted schemas carry an explicit schema_version (Literal where
possible) so journals, caches, and template evolution can detect
incompatible data without silent misinterpretation.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class TaskSize(str, Enum):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    REVISION = "revision"
    APPROVED = "approved"
    INTEGRATED = "integrated"
    TESTING = "testing"
    FAILED = "failed"
    DONE = "done"


class ReviewVerdict(str, Enum):
    APPROVE = "approve"
    REVISE = "revise"


class AcceptanceVerdict(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    INCOMPLETE = "incomplete"  # Verification was skipped — cannot confirm pass


# ---------------------------------------------------------------------------
# Research (new — pre-planning discovery)
# ---------------------------------------------------------------------------

class ResearchFinding(BaseModel):
    """A single finding from the researcher."""
    topic: str
    summary: str
    recommended_approach: str = ""
    libraries: list[str] = Field(default_factory=list)
    apis: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    code_snippets: dict[str, str] = Field(
        default_factory=dict,
        description="label -> snippet showing how to use a library/API"
    )


class ResearchReport(BaseModel):
    """Full research output — feeds into the planner."""
    feasibility: str = Field(description="overall feasibility assessment")
    findings: list[ResearchFinding] = Field(default_factory=list)
    recommended_stack: list[str] = Field(default_factory=list)
    external_services: list[str] = Field(
        default_factory=list,
        description="APIs, Docker containers, databases, etc. that need to be running"
    )
    environment_setup: list[str] = Field(
        default_factory=list,
        description="Steps to prepare the environment (install X, start Y, etc.)"
    )
    reference_repos: list[str] = Field(
        default_factory=list,
        description="GitHub repos to use as implementation reference (owner/name)"
    )
    open_questions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Plan & Task Graph
# ---------------------------------------------------------------------------

class InterfaceContract(BaseModel):
    """A contract between modules — inputs, outputs, and expectations."""
    name: str
    description: str
    inputs: dict[str, str] = Field(default_factory=dict, description="param_name -> type/description")
    outputs: dict[str, str] = Field(default_factory=dict)
    file_path: str = Field(description="Where this interface should live")
    code: str = Field(default="", description="The actual interface code (generated by planner)")


class ModuleSpec(BaseModel):
    """A single buildable unit of work."""
    id: str
    name: str
    description: str
    size: TaskSize
    dependencies: list[str] = Field(default_factory=list)
    interfaces_provided: list[str] = Field(default_factory=list)
    interfaces_consumed: list[str] = Field(default_factory=list)
    file_paths: list[str] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING


class BuildPlan(BaseModel):
    """The full build plan produced by the Planner.

    Contract coverage fields tie the plan to the contract:
      - contract_hash: SHA-256 of the canonical contract JSON
      - goals_covered: maps each contract goal to module IDs that address it
      - non_goals_acknowledged: planner confirms these are out of scope
    """
    schema_version: Literal["1"] = "1"
    project_name: str
    description: str
    archetype: str = Field(
        default="",
        description="Project archetype (python_cli or fastapi_service)"
    )

    # Contract traceability
    contract_hash: str = Field(
        default="",
        description="SHA-256 of the canonical contract JSON — ties plan to a specific contract"
    )
    goals_covered: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Maps each contract goal string to the module IDs that address it"
    )
    non_goals_acknowledged: list[str] = Field(
        default_factory=list,
        description="Contract non-goals the planner confirms it will NOT build"
    )

    # Technical plan
    tech_stack: list[str] = Field(default_factory=list)
    directory_structure: str = Field(default="", description="Planned directory tree as text")
    interfaces: list[InterfaceContract] = Field(default_factory=list)
    modules: list[ModuleSpec] = Field(default_factory=list)
    build_order: list[list[str]] = Field(
        default_factory=list,
        description="Ordered batches of module IDs (parallel within batch)"
    )
    setup_commands: list[str] = Field(
        default_factory=list,
        description="Shell commands to set up the project (pip install, docker run, etc.)"
    )
    test_command: str = Field(
        default="pytest",
        description="Command to run all tests"
    )
    run_command: str = Field(
        default="python main.py",
        description="Command to run the project"
    )
    run_mode: str = Field(
        default="batch",
        description="'batch' for one-shot CLI jobs, 'service' for long-running servers/bots/watchers"
    )


# ---------------------------------------------------------------------------
# Build artifacts
# ---------------------------------------------------------------------------

class BuildArtifact(BaseModel):
    """Output from a builder agent for one module."""
    module_id: str
    files: dict[str, str] = Field(description="file_path -> file_content")
    tests: dict[str, str] = Field(default_factory=dict)
    notes: str = ""


class ReviewResult(BaseModel):
    """Output from a reviewer agent."""
    module_id: str
    verdict: ReviewVerdict
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    notes: str = ""


class IntegrationResult(BaseModel):
    """Output from the integrator agent."""
    modules_integrated: list[str]
    success: bool
    wiring_files: dict[str, str] = Field(default_factory=dict)
    issues: list[str] = Field(default_factory=list)
    notes: str = ""


# ---------------------------------------------------------------------------
# Execution (new — actually running code)
# ---------------------------------------------------------------------------

class ExecResult(BaseModel):
    """Result of executing a command in the project sandbox."""
    command: str
    exit_code: int
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False

    @property
    def success(self) -> bool:
        return self.exit_code == 0


class DebugFix(BaseModel):
    """A fix produced by the debugger agent."""
    diagnosis: str
    file_changes: dict[str, str] = Field(description="file_path -> new full content")
    new_dependencies: list[str] = Field(default_factory=list)
    notes: str = ""


class AcceptanceResult(BaseModel):
    """Output from acceptance testing against the original intent."""
    verdict: AcceptanceVerdict
    criteria_checked: list[str] = Field(default_factory=list)
    criteria_passed: list[str] = Field(default_factory=list)
    criteria_failed: list[str] = Field(default_factory=list)
    notes: str = ""


# ---------------------------------------------------------------------------
# Typed state wrappers for phase outputs
# These import from their respective modules (no circular deps)
# ---------------------------------------------------------------------------

from build_loop.contract import BuildContract
from build_loop.environment import EnvironmentSnapshot
from build_loop.freeform_journal import FreeformJournal
from build_loop.policy import PolicyDecision


class ContractState(BaseModel):
    """Typed wrapper for BuildContract in state."""
    data: BuildContract


class EnvironmentState(BaseModel):
    """Typed wrapper for EnvironmentSnapshot in state."""
    data: EnvironmentSnapshot


class PolicyState(BaseModel):
    """Typed wrapper for PolicyDecision in state."""
    data: PolicyDecision


# ---------------------------------------------------------------------------
# Top-level build state
# ---------------------------------------------------------------------------

class BuildState(BaseModel):
    """The full state of a build loop run. Persisted to disk.

    schema_version is Literal["1"] so loading stale state fails
    validation instead of silently misinterpreting fields.

    contract, environment, and policy are typed models (not raw dicts).
    verification remains dict to avoid circular import with verifier.py.
    """
    schema_version: Literal["1"] = "1"
    idea: str = ""

    # Typed phase outputs (no circular import risk)
    contract: ContractState | None = None
    environment: EnvironmentState | None = None
    policy: PolicyState | None = None
    research: ResearchReport | None = None
    plan: BuildPlan | None = None

    # Build artifacts and analysis
    artifacts: dict[str, BuildArtifact] = Field(default_factory=dict)
    module_exports: dict[str, dict] = Field(
        default_factory=dict,
        description="module_id -> ModuleExports.model_dump(). Populated after each approved module."
    )
    reviews: dict[str, list[ReviewResult]] = Field(default_factory=dict)
    integration: IntegrationResult | None = None
    exec_history: list[ExecResult] = Field(default_factory=list)
    debug_rounds: int = 0
    optimization_count: int = 0

    # Verification stays as dict to avoid circular import with verifier.py
    # (verifier imports ExecResult from schemas)
    verification: dict | None = Field(default=None, description="Serialized VerificationResult")

    acceptance: AcceptanceResult | None = None
    output_dir: str = ""

    # Freeform iteration journal — optional so old state files still load
    freeform_journal: FreeformJournal | None = Field(
        default=None,
        description="Structured issue/attempt journal for freeform runs. None for template_first.",
    )
