"""Shared data models for the build loop.

Every agent reads and writes these structures. This is the contract layer —
if you change a schema, every agent that touches it must be updated.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class TaskSize(str, Enum):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    REVISION = "revision"
    APPROVED = "approved"
    INTEGRATED = "integrated"
    TESTING = "testing"
    FAILED = "failed"
    DONE = "done"


class ReviewVerdict(str, Enum):
    APPROVE = "approve"
    REVISE = "revise"


class AcceptanceVerdict(str, Enum):
    PASS = "pass"
    FAIL = "fail"


# ---------------------------------------------------------------------------
# Research (new — pre-planning discovery)
# ---------------------------------------------------------------------------

class ResearchFinding(BaseModel):
    """A single finding from the researcher."""
    topic: str
    summary: str
    recommended_approach: str = ""
    libraries: list[str] = Field(default_factory=list)
    apis: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    code_snippets: dict[str, str] = Field(
        default_factory=dict,
        description="label -> snippet showing how to use a library/API"
    )


class ResearchReport(BaseModel):
    """Full research output — feeds into the planner."""
    feasibility: str = Field(description="overall feasibility assessment")
    findings: list[ResearchFinding] = Field(default_factory=list)
    recommended_stack: list[str] = Field(default_factory=list)
    external_services: list[str] = Field(
        default_factory=list,
        description="APIs, Docker containers, databases, etc. that need to be running"
    )
    environment_setup: list[str] = Field(
        default_factory=list,
        description="Steps to prepare the environment (install X, start Y, etc.)"
    )
    open_questions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Plan & Task Graph
# ---------------------------------------------------------------------------

class InterfaceContract(BaseModel):
    """A contract between modules — inputs, outputs, and expectations."""
    name: str
    description: str
    inputs: dict[str, str] = Field(default_factory=dict, description="param_name -> type/description")
    outputs: dict[str, str] = Field(default_factory=dict)
    file_path: str = Field(description="Where this interface should live")
    code: str = Field(default="", description="The actual interface code (generated by planner)")


class ModuleSpec(BaseModel):
    """A single buildable unit of work."""
    id: str
    name: str
    description: str
    size: TaskSize
    dependencies: list[str] = Field(default_factory=list)
    interfaces_provided: list[str] = Field(default_factory=list)
    interfaces_consumed: list[str] = Field(default_factory=list)
    file_paths: list[str] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING


class BuildPlan(BaseModel):
    """The full build plan produced by the Planner."""
    project_name: str
    description: str
    tech_stack: list[str] = Field(default_factory=list)
    directory_structure: str = Field(default="", description="Planned directory tree as text")
    interfaces: list[InterfaceContract] = Field(default_factory=list)
    modules: list[ModuleSpec] = Field(default_factory=list)
    build_order: list[list[str]] = Field(
        default_factory=list,
        description="Ordered batches of module IDs (parallel within batch)"
    )
    setup_commands: list[str] = Field(
        default_factory=list,
        description="Shell commands to set up the project (pip install, docker run, etc.)"
    )
    test_command: str = Field(
        default="pytest",
        description="Command to run all tests"
    )
    run_command: str = Field(
        default="python main.py",
        description="Command to run the project"
    )


# ---------------------------------------------------------------------------
# Build artifacts
# ---------------------------------------------------------------------------

class BuildArtifact(BaseModel):
    """Output from a builder agent for one module."""
    module_id: str
    files: dict[str, str] = Field(description="file_path -> file_content")
    tests: dict[str, str] = Field(default_factory=dict)
    notes: str = ""


class ReviewResult(BaseModel):
    """Output from a reviewer agent."""
    module_id: str
    verdict: ReviewVerdict
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    notes: str = ""


class IntegrationResult(BaseModel):
    """Output from the integrator agent."""
    modules_integrated: list[str]
    success: bool
    wiring_files: dict[str, str] = Field(default_factory=dict)
    issues: list[str] = Field(default_factory=list)
    notes: str = ""


# ---------------------------------------------------------------------------
# Execution (new — actually running code)
# ---------------------------------------------------------------------------

class ExecResult(BaseModel):
    """Result of executing a command in the project sandbox."""
    command: str
    exit_code: int
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False

    @property
    def success(self) -> bool:
        return self.exit_code == 0


class DebugFix(BaseModel):
    """A fix produced by the debugger agent."""
    diagnosis: str
    file_changes: dict[str, str] = Field(description="file_path -> new full content")
    new_dependencies: list[str] = Field(default_factory=list)
    notes: str = ""


class AcceptanceResult(BaseModel):
    """Output from acceptance testing against the original intent."""
    verdict: AcceptanceVerdict
    criteria_checked: list[str] = Field(default_factory=list)
    criteria_passed: list[str] = Field(default_factory=list)
    criteria_failed: list[str] = Field(default_factory=list)
    notes: str = ""


# ---------------------------------------------------------------------------
# Top-level build state
# ---------------------------------------------------------------------------

class BuildState(BaseModel):
    """The full state of a build loop run. Persisted to disk."""
    idea: str = ""
    research: ResearchReport | None = None
    plan: BuildPlan | None = None
    artifacts: dict[str, BuildArtifact] = Field(default_factory=dict)
    reviews: dict[str, list[ReviewResult]] = Field(default_factory=dict)
    integration: IntegrationResult | None = None
    exec_history: list[ExecResult] = Field(default_factory=list)
    debug_rounds: int = 0
    acceptance: AcceptanceResult | None = None
    output_dir: str = ""
