"""Shared data models for the build loop.

Every agent reads and writes these structures. This is the contract layer —
if you change a schema, every agent that touches it must be updated.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class TaskSize(str, Enum):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    REVISION = "revision"
    APPROVED = "approved"
    INTEGRATED = "integrated"
    FAILED = "failed"


class ReviewVerdict(str, Enum):
    APPROVE = "approve"
    REVISE = "revise"


# ---------------------------------------------------------------------------
# Plan & Task Graph
# ---------------------------------------------------------------------------

class InterfaceContract(BaseModel):
    """A contract between modules — inputs, outputs, and expectations."""
    name: str
    description: str
    inputs: dict[str, str] = Field(default_factory=dict, description="param_name -> type/description")
    outputs: dict[str, str] = Field(default_factory=dict)
    file_path: str = Field(description="Where this interface should live, e.g. 'src/schemas/hypothesis.py'")
    code: str = Field(default="", description="The actual interface code (generated by planner)")


class ModuleSpec(BaseModel):
    """A single buildable unit of work."""
    id: str
    name: str
    description: str
    size: TaskSize
    dependencies: list[str] = Field(default_factory=list, description="IDs of modules this depends on")
    interfaces_provided: list[str] = Field(default_factory=list, description="Interface names this module implements")
    interfaces_consumed: list[str] = Field(default_factory=list, description="Interface names this module depends on")
    file_paths: list[str] = Field(default_factory=list, description="Expected files this module will create")
    status: TaskStatus = TaskStatus.PENDING


class BuildPlan(BaseModel):
    """The full build plan produced by the Planner."""
    project_name: str
    description: str
    tech_stack: list[str] = Field(default_factory=list)
    directory_structure: str = Field(default="", description="Planned directory tree as text")
    interfaces: list[InterfaceContract] = Field(default_factory=list)
    modules: list[ModuleSpec] = Field(default_factory=list)
    build_order: list[list[str]] = Field(
        default_factory=list,
        description="Ordered list of parallelizable batches, each batch is a list of module IDs"
    )


# ---------------------------------------------------------------------------
# Build artifacts (what builders produce, reviewers judge)
# ---------------------------------------------------------------------------

class BuildArtifact(BaseModel):
    """Output from a builder agent for one module."""
    module_id: str
    files: dict[str, str] = Field(description="file_path -> file_content")
    tests: dict[str, str] = Field(default_factory=dict, description="test_file_path -> test_content")
    notes: str = ""


class ReviewResult(BaseModel):
    """Output from a reviewer agent."""
    module_id: str
    verdict: ReviewVerdict
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    notes: str = ""


class IntegrationResult(BaseModel):
    """Output from the integrator agent."""
    modules_integrated: list[str]
    success: bool
    wiring_files: dict[str, str] = Field(default_factory=dict, description="Any glue code created")
    issues: list[str] = Field(default_factory=list)
    notes: str = ""


# ---------------------------------------------------------------------------
# Top-level build state
# ---------------------------------------------------------------------------

class BuildState(BaseModel):
    """The full state of a build loop run. Persisted to disk."""
    idea: str = ""
    clarifications: list[dict[str, str]] = Field(default_factory=list)
    plan: BuildPlan | None = None
    artifacts: dict[str, BuildArtifact] = Field(default_factory=dict, description="module_id -> artifact")
    reviews: dict[str, list[ReviewResult]] = Field(default_factory=dict, description="module_id -> review history")
    integration: IntegrationResult | None = None
    output_dir: str = ""
